steps:
  - id: "Test"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Branch name: $_BRANCH_NAME"

steps:
  - id: "Clone"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Cloning repository..."
        git clone https://github.com/dearmesh/dap-composer-cicd.git /workspace/dap-composer-cicd
        cd /workspace/dap-composer-cicd
        git checkout $BRANCH_NAME

# Step 2: Check for changes in the dags/ folder
  - id: "Detect-Changes"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Checking for changes in the dags/ folder..."
        if ! git diff --name-only HEAD~1 HEAD | grep '^dags/'; then
          echo "No changes in DAG files. Exiting."
          exit 0
        fi

# Step 3: Sync DAGs to the appropriate Composer bucket
  - id: "Upload"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo $_BRANCH_NAME
        echo "Deploying DAGs to the Composer bucket for branch: $_BRANCH_NAME"
        case "$_BRANCH_NAME" in 
          "dev")
            TARGET_BUCKET="gs://asia-southeast2-dev-env-4cd8345a-bucket/dags"
            ;;
          "sit")
            TARGET_BUCKET="gs://asia-southeast2-sit-env-f9237651-bucket/dags"
            ;;
          "uat")
            TARGET_BUCKET="gs://asia-southeast2-uat-env-bucket/dags"
            ;;
          "production")
            TARGET_BUCKET="gs://asia-southeast2-prod-env-bucket/dags"
            ;;
          *)
            echo "Error: Unsupported branch $_BRANCH_NAME"
            exit 1
            ;;
        esac
        echo "Syncing DAGs to $TARGET_BUCKET..."
        gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags "$TARGET_BUCKET" 


  - id: "Debug"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Environment variables:"
        env


substitutions:
  _BRANCH_NAME: "main"

options:
  logging: CLOUD_LOGGING_ONLY