steps:
  - id: "Test"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Branch name: $_BRANCH_NAME"

steps:
  # Step 1: Clone the repository from GitHub
  - id: "Clone"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Cloning repository from GitHub..."
        git clone https://github.com/dearmesh/dap-composer-cicd.git /dap-composer-cicd
        cd /dap-composer-cicd
        git checkout $_BRANCH_NAME 

substitutions:
  _BRANCH_NAME: "main"

options:
  logging: CLOUD_LOGGING_ONLY