steps:
  - id: "Test"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Branch name: $_BRANCH_NAME"

steps:
  - id: "Clone"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Cloning repository..."
        git clone https://github.com/dearmesh/dap-composer-cicd.git /workspace/dap-composer-cicd
        cd /workspace/dap-composer-cicd
        git checkout $BRANCH_NAME


substitutions:
  _BRANCH_NAME: "main"

options:
  logging: CLOUD_LOGGING_ONLY